package zhu.ProxyChecker;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;

/**
 *
 * @author Zhu
 */
public class MainFrame extends javax.swing.JFrame
{

    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
        initComponents();
        //窗体放屏幕中间
        setLocationRelativeTo(null);
        //表允许自动排序
        //proxyTable.setAutoCreateRowSorter(true);
        //检测时的一些按钮可用性设置
        Application.addCheckStartedListener(new CheckStartedListener() 
        {
            @Override
            public void action()
            {
                SwingUtilities.invokeLater(new Runnable()
                {
                    @Override
                    public void run()
                    {
                        checkAllButton.setEnabled(false);
                        checkAllMenuItem.setEnabled(false);
                        checkButton.setEnabled(false);
                        checkMenuItem.setEnabled(false);
                        stopCheckButton.setEnabled(true);
                        stopCheckMenuItem.setEnabled(true);
                    }
                });
            }
        });
        //检测结束后一些按钮的可用性设置
        Application.addCheckFinishListener(new CheckFinishListener()
        {
            @Override
            public void action()
            {
                SwingUtilities.invokeLater(new Runnable()
                {
                    @Override
                    public void run()
                    {
                        checkAllButton.setEnabled(true);
                        checkAllMenuItem.setEnabled(true);
                        checkButton.setEnabled(true);
                        checkMenuItem.setEnabled(true);
                        stopCheckButton.setEnabled(false);
                        stopCheckMenuItem.setEnabled(false);
                    }
                });

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proxyScrollPanel = new javax.swing.JScrollPane();
        proxyTable = new javax.swing.JTable();
        proxyPanel = new javax.swing.JPanel();
        checkButton = new javax.swing.JButton();
        checkAllButton = new javax.swing.JButton();
        stopCheckButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        addMulButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        deleteAllButton = new javax.swing.JButton();
        deleteFailButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        exportButton10 = new javax.swing.JButton();
        optionButton1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        importMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        checkMenu = new javax.swing.JMenu();
        checkMenuItem = new javax.swing.JMenuItem();
        checkAllMenuItem = new javax.swing.JMenuItem();
        stopCheckMenuItem = new javax.swing.JMenuItem();
        addMenu = new javax.swing.JMenu();
        addMenuItem = new javax.swing.JMenuItem();
        addMulMenuItem = new javax.swing.JMenuItem();
        filterMenu = new javax.swing.JMenu();
        deleteMenuItem = new javax.swing.JMenuItem();
        deleteAllMenuItem = new javax.swing.JMenuItem();
        delteFailMenuItem = new javax.swing.JMenuItem();
        optionMenu = new javax.swing.JMenu();
        optionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("代理猪手");
        setName("mainFrame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                saveInformation(evt);
            }
        });

        proxyTable.setModel(ProxyTableModel.getModel());
        proxyTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        proxyScrollPanel.setViewportView(proxyTable);

        getContentPane().add(proxyScrollPanel, java.awt.BorderLayout.CENTER);

        proxyPanel.setLayout(new javax.swing.BoxLayout(proxyPanel, javax.swing.BoxLayout.Y_AXIS));

        checkButton.setText("检验选中");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSelected(evt);
            }
        });
        proxyPanel.add(checkButton);

        checkAllButton.setText("检验全部");
        checkAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCheckAll(evt);
            }
        });
        proxyPanel.add(checkAllButton);

        stopCheckButton.setText("停止检验");
        stopCheckButton.setActionCommand("检验全部");
        stopCheckButton.setEnabled(false);
        stopCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopCheck(evt);
            }
        });
        proxyPanel.add(stopCheckButton);

        addButton.setText("添加代理");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAddDialog(evt);
            }
        });
        proxyPanel.add(addButton);

        addMulButton.setText("批量添加");
        addMulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAddmulDialog(evt);
            }
        });
        proxyPanel.add(addMulButton);

        deleteButton.setText("删除选中");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSelect(evt);
            }
        });
        proxyPanel.add(deleteButton);

        deleteAllButton.setText("删除全部");
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAll(evt);
            }
        });
        proxyPanel.add(deleteAllButton);

        deleteFailButton.setText("删除失败");
        deleteFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFailed(evt);
            }
        });
        proxyPanel.add(deleteFailButton);

        importButton.setText("批量导入");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importResult(evt);
            }
        });
        proxyPanel.add(importButton);

        exportButton10.setText("批量导出");
        exportButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportResult(evt);
            }
        });
        proxyPanel.add(exportButton10);

        optionButton1.setText("设置选项");
        optionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openOptionDialog(evt);
            }
        });
        proxyPanel.add(optionButton1);

        getContentPane().add(proxyPanel, java.awt.BorderLayout.EAST);

        menuBar.setName("");

        fileMenu.setText("文件");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importResult(evt);
            }
        });

        importMenuItem.setText("批量导入");
        importMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importResult(evt);
            }
        });
        fileMenu.add(importMenuItem);

        exportMenuItem.setText("批量导出");
        exportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportResult(evt);
            }
        });
        fileMenu.add(exportMenuItem);
        fileMenu.add(jSeparator1);

        exitMenuItem.setText("退出");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        checkMenu.setText("检验");

        checkMenuItem.setText("检验选中");
        checkMenu.add(checkMenuItem);

        checkAllMenuItem.setText("检验全部");
        checkAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCheckAll(evt);
            }
        });
        checkMenu.add(checkAllMenuItem);

        stopCheckMenuItem.setText("停止检验");
        stopCheckMenuItem.setEnabled(false);
        stopCheckMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopCheck(evt);
            }
        });
        checkMenu.add(stopCheckMenuItem);

        menuBar.add(checkMenu);

        addMenu.setText("添加");

        addMenuItem.setText("添加代理");
        addMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAddDialog(evt);
            }
        });
        addMenu.add(addMenuItem);

        addMulMenuItem.setText("批量添加");
        addMulMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAddmulDialog(evt);
            }
        });
        addMenu.add(addMulMenuItem);

        menuBar.add(addMenu);

        filterMenu.setText("筛选");

        deleteMenuItem.setText("删除选择");
        filterMenu.add(deleteMenuItem);

        deleteAllMenuItem.setText("删除全部");
        deleteAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAll(evt);
            }
        });
        filterMenu.add(deleteAllMenuItem);

        delteFailMenuItem.setText("删除无效");
        delteFailMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFailed(evt);
            }
        });
        filterMenu.add(delteFailMenuItem);

        menuBar.add(filterMenu);

        optionMenu.setText("设置");

        optionMenuItem.setText("设置选项");
        optionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openOptionDialog(evt);
            }
        });
        optionMenu.add(optionMenuItem);

        menuBar.add(optionMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void openOptionDialog(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openOptionDialog
    {//GEN-HEADEREND:event_openOptionDialog
        new OptionDialog(this,true).setVisible(true);
    }//GEN-LAST:event_openOptionDialog

    private void openAddDialog(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openAddDialog
    {//GEN-HEADEREND:event_openAddDialog
        new AddDialog(this,true).setVisible(true);
    }//GEN-LAST:event_openAddDialog

    private void openAddmulDialog(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openAddmulDialog
    {//GEN-HEADEREND:event_openAddmulDialog
        new AddMulDialog(this,true).setVisible(true);
    }//GEN-LAST:event_openAddmulDialog

    private void saveInformation(java.awt.event.WindowEvent evt)//GEN-FIRST:event_saveInformation
    {//GEN-HEADEREND:event_saveInformation
        Application.stopCheck();
        Config.writeConfig();
        Application.writeResult();
    }//GEN-LAST:event_saveInformation

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitMenuItemActionPerformed
    {//GEN-HEADEREND:event_exitMenuItemActionPerformed
        saveInformation(null);
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void startCheckAll(java.awt.event.ActionEvent evt)//GEN-FIRST:event_startCheckAll
    {//GEN-HEADEREND:event_startCheckAll
        Application.startCheckAll();
    }//GEN-LAST:event_startCheckAll

    private void stopCheck(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stopCheck
    {//GEN-HEADEREND:event_stopCheck
        Application.stopCheck();
    }//GEN-LAST:event_stopCheck

    private void removeAll(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeAll
    {//GEN-HEADEREND:event_removeAll
        Application.cleanAll();
        proxyTable.repaint();
    }//GEN-LAST:event_removeAll

    private void removeFailed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeFailed
    {//GEN-HEADEREND:event_removeFailed
        Application.cleanFailed();
        proxyTable.repaint();
    }//GEN-LAST:event_removeFailed

    private void removeSelect(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeSelect
    {//GEN-HEADEREND:event_removeSelect
        int rowIndex = proxyTable.getSelectedRow();
        Application.proxyPool.remove(rowIndex);
        proxyTable.repaint();
    }//GEN-LAST:event_removeSelect

    private void checkSelected(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkSelected
    {//GEN-HEADEREND:event_checkSelected
        int rowIndex = proxyTable.getSelectedRow();
        //System.out.println(rowIndex);
        Application.proxyChecker.startCheck(
                   Application.proxyPool.getProxy(rowIndex));
        proxyTable.repaint();
    }//GEN-LAST:event_checkSelected

    private void importResult(java.awt.event.ActionEvent evt)//GEN-FIRST:event_importResult
    {//GEN-HEADEREND:event_importResult
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        File file = fileChooser.getSelectedFile();
        Application.readResult(file);
    }//GEN-LAST:event_importResult

    private void exportResult(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exportResult
    {//GEN-HEADEREND:event_exportResult
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showSaveDialog(this);
        File file = fileChooser.getSelectedFile();
        Application.writeResult(file);
    }//GEN-LAST:event_exportResult

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JMenu addMenu;
    private javax.swing.JMenuItem addMenuItem;
    private javax.swing.JButton addMulButton;
    private javax.swing.JMenuItem addMulMenuItem;
    private javax.swing.JButton checkAllButton;
    private javax.swing.JMenuItem checkAllMenuItem;
    private javax.swing.JButton checkButton;
    private javax.swing.JMenu checkMenu;
    private javax.swing.JMenuItem checkMenuItem;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JMenuItem deleteAllMenuItem;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteFailButton;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem delteFailMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton exportButton10;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu filterMenu;
    private javax.swing.JButton importButton;
    private javax.swing.JMenuItem importMenuItem;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton optionButton1;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JMenuItem optionMenuItem;
    private javax.swing.JPanel proxyPanel;
    private javax.swing.JScrollPane proxyScrollPanel;
    private javax.swing.JTable proxyTable;
    private javax.swing.JButton stopCheckButton;
    private javax.swing.JMenuItem stopCheckMenuItem;
    // End of variables declaration//GEN-END:variables
}
