package zhu.ProxyChecker;

import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zhu
 */
public class OptionDialog extends javax.swing.JDialog
{

    /**
     * Creates new form OptionDialog
     */
    public OptionDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(Application.mainFrame);
        readTimeoutTextField.setDocument(new NumOnlyDocument());
        connectTimeoutTextField.setDocument(new NumOnlyDocument());
        threadCountTextField.setDocument(new NumOnlyDocument());
        lookComboBox.removeAllItems();
        for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
        {
            lookComboBox.addItem(info.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        urlTextField = new javax.swing.JTextField();
        keywordTextField = new javax.swing.JTextField();
        connectTimeoutTextField = new javax.swing.JTextField();
        readTimeoutTextField = new javax.swing.JTextField();
        threadCountTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lookComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("选项");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                loadConfig(evt);
            }
        });

        jLabel1.setText("验证URL");

        jLabel2.setText("验证关键字");

        jLabel3.setText("链接超时(ms)");

        jLabel4.setText("验证超时(ms)");

        jLabel5.setText("并发线程数");
        jLabel5.setToolTipText("");

        resetButton.setText("恢复默认");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backDefaultConfig(evt);
            }
        });

        okButton.setText("确认");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeConfig(evt);
            }
        });

        cancelButton.setText("取消");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeDialog(evt);
            }
        });

        connectTimeoutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectTimeoutTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("界面风格(重启后生效):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(urlTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(keywordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(connectTimeoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(readTimeoutTextField)
                            .addComponent(threadCountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lookComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(threadCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(readTimeoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectTimeoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void connectTimeoutTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_connectTimeoutTextFieldActionPerformed
    {//GEN-HEADEREND:event_connectTimeoutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectTimeoutTextFieldActionPerformed

    private void changeConfig(java.awt.event.ActionEvent evt)//GEN-FIRST:event_changeConfig
    {//GEN-HEADEREND:event_changeConfig
        Config.urlString = urlTextField.getText();
        Config.keyword = keywordTextField.getText();
        Config.readTimeout = Integer.valueOf(readTimeoutTextField.getText());
        Config.connectTimout = Integer.valueOf(connectTimeoutTextField.getText());
        Config.threadCount = Integer.valueOf(threadCountTextField.getText());
        Config.lookAndFeel = lookComboBox.getSelectedItem().toString();
        Config.writeConfig();
        loadConfig(null);
        dispose();
    }//GEN-LAST:event_changeConfig

    private void loadConfig(java.awt.event.WindowEvent evt)//GEN-FIRST:event_loadConfig
    {//GEN-HEADEREND:event_loadConfig
        urlTextField.setText(Config.urlString);
        keywordTextField.setText(Config.keyword);
        readTimeoutTextField.setText(String.valueOf(Config.readTimeout));
        connectTimeoutTextField.setText(String.valueOf(Config.connectTimout));
        threadCountTextField.setText(String.valueOf(Config.threadCount));
        lookComboBox.setSelectedItem(Config.lookAndFeel);
    }//GEN-LAST:event_loadConfig

    private void closeDialog(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeDialog
    {//GEN-HEADEREND:event_closeDialog
        dispose();
    }//GEN-LAST:event_closeDialog

    private void backDefaultConfig(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backDefaultConfig
    {//GEN-HEADEREND:event_backDefaultConfig
        Config.setDefaultConfig();
        Config.writeConfig();
        loadConfig(null);
    }//GEN-LAST:event_backDefaultConfig

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField connectTimeoutTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField keywordTextField;
    private javax.swing.JComboBox lookComboBox;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField readTimeoutTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField threadCountTextField;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables

    class NumOnlyDocument extends PlainDocument
    {
        @Override
        public void insertString(int offset, String s, AttributeSet attrSet)
                                                    throws BadLocationException 
        {
            try 
            {
                Integer.parseInt(s);
            }
            catch (NumberFormatException ex) 
            {
                return;
            }
            super.insertString(offset, s, attrSet);
        }
}
}
